Grpc
Pivot-Studio/pivot-chat pull request #26
Opened 2022-11-12 09:33 UTC by husterdjx

2022-11-12 09:34 UTC, Chronostasys requested changes

2022-11-12 09:34 UTC, Chronostasys commented on service/conn-manager.go
> -	"errors"
生成的文件不要放项目里，加入gitignore

2022-11-12 09:51 UTC, husterdjx commented on service/conn-manager.go
> -	"errors"
已解决

2022-11-21 07:50 UTC, Chronostasys approved these changes
LGTM

2024-09-25 17:59 UTC, closed without merging